apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rockylinux-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
#  storageClassName: rook-ssdfs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rockylinux-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rockylinux
  template:
    metadata:
      labels:
        app: rockylinux
    spec:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      - effect: NoExecute
        key: node-role.kubernetes.io/etcd
        operator: Exists
      containers:
      - name: rockylinux
        image: rockylinux:9.3
        command: ["/bin/bash", "-c", "sleep infinity"]
        volumeMounts:
        - mountPath: "/home"
          name: rockylinux-storage
      volumes:
      - name: rockylinux-storage
        persistentVolumeClaim:
          claimName: rockylinux-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: rockylinux-service
  namespace: default
spec:
  selector:
    app: rockylinux
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
  type: LoadBalancer
  loadBalancerIP: 192.168.16.11

