# kubectl -n ingress create secret tls ingress-tls --key=ingress.key --cert=ingress.crt
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: ingress
spec:
  defaultCertificate:
    secretName: ingress-tls
  certificates:
    - secretName: hybridocr-tls

