# helm install traefik traefik/traefik -f traefik.yaml
namespaceOverride: ingress
deployment:
  replicas: 1
tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
ports:
  web:
    protocol: TCP
    port: 8000
    # containerPort: 8000
    exposedPort: 80
    nodePort: 80
    redirectTo:
      port: websecure
  websecure:
    protocol: TCP
    port: 8443
    containerPort: 8443
    nodePort: 443
service:
  type: NodePort

