apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: production
  namespace: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v18.2.2
  dataDirHostPath: /data/k8s/rook-ceph/production
  mon:
    count: 3
    allowMultiplePerNode: false
  dashboard:
    enabled: true
  network:
    provider: host
    requireMsgr2: true
    selectors:
      public: "192.168.16.0/24"
      cluster: "192.168.17.0/24"
  storage:
    useAllNodes: false
    useAllDevices: false
    config:
      encryptedDevice: "true"
    nodes:
      - name: "pm1.ezekielnewren.com"
        devices:
          - name: Samsung_SSD_870_QVO_8TB_S5VUNJ0TA00068Z
            fullpath: "/dev/disk/by-id/ata-Samsung_SSD_870_QVO_8TB_S5VUNJ0TA00068Z"
      - name: "pm2.ezekielnewren.com"
        devices:
          - name: Samsung_SSD_870_QVO_8TB_S5VUNJ0TA00775E
            fullpath: "/dev/disk/by-id/ata-Samsung_SSD_870_QVO_8TB_S5VUNJ0TA00775E"
      - name: "pm3.ezekielnewren.com"
        devices:
          - name: Samsung_SSD_870_QVO_8TB_S5VUNJ0T803861W
            fullpath: "/dev/disk/by-id/ata-Samsung_SSD_870_QVO_8TB_S5VUNJ0T803861W"
  placement:
    all:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
        - effect: NoExecute
          key: node-role.kubernetes.io/etcd
          operator: Exists
