apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: ssdfs
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 3
    parameters:
      pg_num: "128"
      pgp_num: "128"
    crushRoot: default
    failureDomain: host
    deviceClass: ssd
  dataPools:
    - name: replicated
      replicated:
        size: 3
      parameters:
        pg_num: "128"
        pgp_num: "128"
      crushRoot: default
      failureDomain: host
      deviceClass: ssd
  preserveFilesystemOnDelete: true
  metadataServer:
    activeCount: 1
    activeStandby: true
    placement:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      - effect: NoExecute
        key: node-role.kubernetes.io/etcd
        operator: Exists

