apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba
  namespace: rook-ceph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samba
  template:
    metadata:
      labels:
        app: samba
    spec:
      containers:
      - name: samba
        image: docker.ezekielnewren.com/ceph_to_samba
#        imagePullPolicy: Always
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_ADMIN
            # - NET_BIND_SERVICE
        env:
        - name: SAMBA_UID
          value: "1000"
        - name: SAMBA_GID
          value: "1000"
        - name: SAMBA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: samba-password
              key: password
        ports:
        - containerPort: 4445
        volumeMounts:
        - name: dev-fuse
          mountPath: /dev/fuse
      volumes:
      - name: dev-fuse
        hostPath:
          path: /dev/fuse
          type: CharDevice
---
apiVersion: v1
kind: Service
metadata:
  name: samba-service
  namespace: rook-ceph
spec:
  type: NodePort
  selector:
    app: samba
  ports:
    - port: 445
      targetPort: 4445
      nodePort: 445
      protocol: TCP

