apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifactory
  namespace: artifactory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artifactory
  template:
    metadata:
      labels:
        app: artifactory
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      initContainers:
        - name: init-artifactory
          image: busybox
          command:
            - sh
            - -c
            - chown -R 1030:1030 /opt/jfrog/artifactory
          volumeMounts:
          - name: artifactory-data
            mountPath: /opt/jfrog/artifactory
      containers:
        - name: artifactory
          image: docker.bintray.io/jfrog/artifactory-oss:latest
          ports:
          - containerPort: 8081
          volumeMounts:
          - name: artifactory-data
            mountPath: /var/opt/jfrog/artifactory
      volumes:
      - name: artifactory-data
        persistentVolumeClaim:
          claimName: artifactory-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: artifactory
  namespace: artifactory
spec:
  selector:
    app: artifactory
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: artifactory-ingress
  namespace: artifactory
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: artifactory.ezekielnewren.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: artifactory
            port:
              number: 8081

