apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-dangoreus-pvc
  namespace: fun
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: factorio-dangoreus-pvc-init
  namespace: fun
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: copy-whitelist
        image: alpine
        command: ["/bin/ash", "-c"]
        args:
        - "mkdir -p /factorio/config; cp /mnt/server-whitelist.json /factorio/config/server-whitelist.json"
        volumeMounts:
        - name: factorio-dangoreus-storage
          mountPath: /factorio
        - name: server-whitelist-volume
          mountPath: /mnt/server-whitelist.json
          subPath: server-whitelist.json
      volumes:
      - name: factorio-dangoreus-storage
        persistentVolumeClaim:
          claimName: factorio-dangoreus-pvc
      - name: server-whitelist-volume
        configMap:
          name: factorio-whitelist

