apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorio-dangoreus
  namespace: fun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: factorio-dangoreus
  template:
    metadata:
      labels:
        app: factorio-dangoreus
    spec:
      containers:
      - name: factorio-dangoreus
        image: factoriotools/factorio:1.1.109
        env:
        #- name: LOAD_LATEST_SAVE
        #  value: "dangoreus"
        - name: UPDATE_MODS_ON_START
          value: "false"
        - name: USERNAME
          valueFrom:
            configMapKeyRef:
              name: factorio-username
              key: USERNAME
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: factorio-token
              key: TOKEN
        ports:
        - containerPort: 34197
          protocol: UDP
        volumeMounts:
        - name: factorio-dangoreus-storage
          mountPath: /factorio
      volumes:
      - name: factorio-dangoreus-storage
        persistentVolumeClaim:
          claimName: factorio-dangoreus-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: factorio-dangoreus
  namespace: fun
spec:
  type: NodePort
  selector:
    app: factorio-dangoreus
  ports:
  - protocol: UDP
    port: 34198
    targetPort: 34197
    nodePort: 34198

